### ISSUE TITLE
DSA or RSA bigger than 2048 bits

### ISSUE THREAD

**Issue by freddyyeddy** [trustcrypto/onlykey-agent#9]
Several web-hosts require a DSA or RSA bigger than 2048 bits for their ssh keys (Siteground for example). My main use case for the OnlyKey-Agent would be SSH into a clients web host to deploy via git etcetera. Can the OnlyKey generate such keys, and if not will it ever be implemented?

**Comment by M-Pixel** [comment]
There's no such thing as a ED25519 key larger than 256 bits (512 for the public key), as far as I've read, so if your host supports that curve at all then it should support OnlyKey and onlykey-agent in their current state.

OnlyKey doesn't support generating RSA on-device and probably never will, because it would take a very long time for it to do so, but you can absolutely load a 4096 RSA key onto the OnlyKey.  `onlykey-agent` doesn't currently support using RSA Keys, although adding RSA support to it is totally possible and would be a smallish project.

**Comment by freddyyeddy** [comment]
I appreciate the information. It would be sweet if onlykey-agent supported
using rsa keys i generated and loaded onto it.

**Comment by onlykey** [comment]
We have RSA keys on the roadmap for onlykey agent, in the readme
